# https://travis-ci.org/tornadoweb/tornado
language: python
python:
    - 2.7
    - 2.7.12
    
env:

  - DB=mysql56

  
 
install: "pip install -r requirements.txt"
script:
  - env | grep DB

  - bash -c "if [ '$DB' = 'mysql56' ]; then sudo ./scripts/install_mysql56.sh; fi"


