language: python
python:
    - 2.7
    - 2.7.12
    
install:
  - pip install --upgrade pip



script:
    
  - sudo apt-get remove --purge mysql*
  - sudo apt-get autoremove
  - sudo apt-get autoclean
  
